### ISSUE TITLE
2.0 breaks the GUI

### ISSUE THREAD

**Issue by fyah** [nextcloud/ocsms#280]
### Steps to reproduce
1. Upgrade/install ocsms

### Expected behaviour
The application shall open

### Actual behaviour
The application is not openning at all

### Server configuration

Nextcloud 14.0.3

### Logs

Left panel:
```
Aucun contact trouvé.            
{{ contact.label }}{{ contact.unread > 0 ? ' (' + contact.unread + ') ' : '' }}
```

Right panel:
```
{{ selectedContact.label | firstCharacter }}
{{ selectedContact.label }} 
{{ selectedContact.opt_numbers }}
{{ messages.length }} message(s) affiché(s) sur {{ totalMessageCount }} message(s) stocké(s) dans la base de données.
```

**Comment by russlan-kravec** [comment]
I have the same problem

**Comment by nerzhul** [comment]
hello, it seems it's a packaging issue in release, again, no problem in devel mode. I will verify how to package it properly

**Comment by andmor-** [comment]
The uglify process is not picking up all the files during the build as it [should](https://github.com/nextcloud/ocsms/blob/master/gulpfile.js#L6). It only seems to pick up settings.js
As a workaround you can run `uglifyjs devel/*.js > app.min.js` on a project checkout and deploy the generated `app.min.js`

**Comment by nerzhul** [comment]
it's not uglifyjs anymore but gulp :)

**Comment by fyah** [comment]
brilliant, thanks !

**Comment by nerzhul** [comment]
or not :) it's a fail in the release packaging test

**Comment by NodokaMurmevent** [comment]
i updated to 2.0.2 and i have the interface now.

**Comment by binome333** [comment]
I've just seen that I also fall into this bug.

devel tool on firefox complains about missing scripts in js/devel and indeed, there is no "devel" subfolder in "js" folder of plugin.
So I copied "devel" folder from git repo to plugin "js" folder, and the problem is solved !

Nextcloud 14.0.4
ocsms 2.1.0 from nextcloud app store (also tried 2.0.2 with same problem)

**Comment by nerzhul** [comment]
the packaging issue is anoying,  i see a problem with JS ordering when packaging, i should fix it. It's a problem in the release process. devel is using non minified JS

**Comment by nerzhul** [comment]
i will release 2.1.1 with a packaging fix, sorry for the delay

**Comment by nerzhul** [comment]
Can someone test https://github.com/nextcloud/ocsms/releases/tag/2.1.1 ? It seems okay to me but i want to be sure before publishing on the app store.
Drop the ocsms folder and replace it with the https://github.com/nextcloud/ocsms/releases/download/2.1.1/ocsms-2.1.1.tar.gz release

**Comment by smirkybg** [comment]
It's improved but still not good enough.
The UI loads on Firefox fine, but the SMS entries are loading constantly so you cannot see the content.
The UI loads on Chromium partially fine, the icon entries overlap each other and it loads constantly.
https://www.smirky.net/upload/storage/20181222_135142_2018-12-22-13:51:30.png

**Comment by nerzhul** [comment]
Fixed in the new https://github.com/nextcloud/ocsms/releases/download/2.1.1/ocsms-2.1.1.tar.gz upload

**Comment by smirkybg** [comment]
Weeeeeeeeeeell...
https://www.smirky.net/upload/storage/20181222_171735_2018-12-22-17:17:24.png

**Comment by nerzhul** [comment]
wtf

**Comment by nerzhul** [comment]
https://github.com/nextcloud/ocsms/releases/download/2.1.1/ocsms-2.1.1.tar.gz is okay now ...

**Comment by smirkybg** [comment]
It works fine now. The icons are still overlapping in Chromium, but I don't have a problem with that :)

**Comment by nerzhul** [comment]
thanks :) i will try to reinforce the release process starting on next release
